
font_family      JetBrains Mono
font_size 14.0
window_padding_width 10

foreground #85e89d
background #171718
background_opacity 0.85
selection_foreground #ffffff
selection_background #14b8a6



# Black
color0 #0b0c15
# Red
color1 #d2556c
# Green
color2 #00e6f7
# Yellow
color3 #efb184
# Blue
color4 #6ca1f3
# Magenta
color5 #b78df0
# Cyan
color6 #e70505
# White
color7 #c0caf5

# # bright colors

# Bright Black
color8  #39404a
# Bright Red
color9  #f7768e
# Bright Green
color10 #85e89d
# Bright Yellow
color11 #f4cf8d
# Bright Blue
color12 #8fb9ff
# Bright Magenta
color13 #d9a3ff
# Bright Cyan
color14 #8fd3ff
# Bright White
color15 #f0f3f6

