
### Автозагрузка ###
exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
exec-once = ~/.azotebg-hyprland
exec-once = lxsession

$terminal = kitty                           # Терминал
$fileManager = thunar                       # Файловый менеджер
$menu = ~/.config/wofi/wofi-toggle.sh       # Меню
$screenlock = hyprlock                      # Экран блокировки
$pavucontrol = org.pulseaudio.pavucontrol   # Управление звуковыми устройствами
windowrule {
    name = firefox
    match:class = ^(firefox)$
    match:title = ^(Библиотека)$
    float = on
    center = on
    animation = popin    
    stay_focused = on
}
windowrule {
    name = kitty
    match:class = ^($terminal)$
    monitor = DP-2, HDMI-A-1       # или DP-1, eDP-1 — имя вашего монитора
    workspace = 4
    animation = popin    
}
windowrule {
    name = wofi
    match:class = ^(wofi)$
    monitor = DP-2, HDMI-A-1       # или DP-1, eDP-1 — имя вашего монитора
    workspace = current     # или номер workspace
    animation = popin
    stay_focused = on
}
windowrule {
    name = nwtui
    match:class = ^($terminal)$
    match:title = ^(Wi-Fi Manager)$
    size = 1280 720
    monitor = current       
    workspace = current     
    float = on
    center = on
    animation = popin    
    stay_focused = on
}
windowrule {
    name = $pavucontrol
    match:class = ^($pavucontrol)$
    size = 1280 720
    monitor = current       
    workspace = current     
    float = on
    center = on
    animation = popin    
    stay_focused = off
    opacity = 0.95
}
windowrule {
    name = VirtualBox Machine
    match:class = ^(VirtualBox Machine)$
    monitor = HDMI-A-1       
    workspace = 2     
    animation = popin    
    stay_focused = off
}
windowrule {
    name = sddm-greeter
    match:class = ^(sddm-greeter)$
    monitor = HDMI-A-1       # или DP-1, eDP-1 — имя вашего монитора
    workspace = 2     # или номер workspace
    animation = popin
    stay_focused = on
    size = 1280 720
}

windowrule {
    name = appWC
    match:class = ^(appWC)$
    monitor = HDMI-A-1       # или DP-1, eDP-1 — имя вашего монитора
    workspace = 2     # или номер workspace
    animation = popin
    stay_focused = on
}
windowrule {
    name = Thunar
    match:class = ^(Thunar|thunar)$
    animation = popin
    stay_focused = off
    opacity = 0.85
}
windowrule {
    name = Thunar_rename
    match:class = ^(Thunar|thunar)$
    match:title = ^(Переименовать .*)$
    animation = popin
    stay_focused = on
    size = 600 140
    float = on
    center = on
}

# windowrule {
#     name = code
#     match:class = ^(code)$
#     animation = popin
#     stay_focused = off
#     opacity = 1
# }

windowrule {
    name = razergenie
    match:class = ^(xyz.z3ntu.razergenie)$
    animation = popin
    stay_focused = off
    opacity = 0.9
}
windowrule {
    name = lxpolkit
    match:class = ^(lxpolkit)$
    animation = popin
    stay_focused = on
    opacity = 0.85
}
# windowrule {
#     name = org.kde.ark
#     match:class = ^(org.kde.ark)$
#     animation = popin
#     stay_focused = off
#     opacity = 0.9
# }