
$terminal = kitty                           # Терминал
$fileManager = thunar                       # Файловый менеджер
$menu = ~/.config/wofi/wofi-toggle.sh       # Меню
$screenlock = hyprlock                      # Экран блокировки
$pavucontrol = org.pulseaudio.pavucontrol   # Управление звуковыми устройствами
windowrule {
    name = firefox
    match:class = ^(firefox)$
    match:title = ^(Библиотека)$
    float = on
    center = on
    animation = popin    
    stay_focused = on
}
windowrule {
    name = kitty
    match:class = ^($terminal)$
    monitor = DP-2, HDMI-A-1       # или DP-1, eDP-1 — имя вашего монитора
    workspace = 4
    animation = popin    
}
windowrule {
    name = wofi
    match:class = ^(wofi)$
    monitor = DP-2, HDMI-A-1       # или DP-1, eDP-1 — имя вашего монитора
    workspace = current     # или номер workspace
    animation = popin
    stay_focused = on
}
windowrule {
    name = nwtui
    match:class = ^($terminal)$
    match:title = ^(Wi-Fi Manager)$
    size = 1280 720
    monitor = current       
    workspace = current     
    float = on
    center = on
    animation = popin    
    stay_focused = on
}
windowrule {
    name = $pavucontrol
    match:class = ^($pavucontrol)$
    size = 1280 720
    monitor = current       
    workspace = current     
    float = on
    center = on
    animation = popin    
    stay_focused = off
}
windowrule {
    name = VirtualBox Machine
    match:class = ^(VirtualBox Machine)$
    monitor = HDMI-A-1       
    workspace = 2     
    animation = popin    
    stay_focused = off
}