general {
  col.active_border = rgb(0,247,255) rgb(0,255,110) 45deg                    # Цвет рамки активного окна
  col.inactive_border = rgb(44,28,84)                                          # Цвет рамки остальных окон
}
