-- Generated by nwg-displays on 2026-06-17 at 18:11:50. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "2560x1440@143.86",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "2691x143",
    scale = 1.0
})
