[ST2426V00601415]
backlight_active = True
backlight_brightness = 26
backlight_effect = static
backlight_colors = 0 255 255 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1

[332203B02701552]
backlight_active = True
backlight_brightness = 26
backlight_effect = static
backlight_colors = 0 255 255 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1

[632147U07701340]
backlight_active = True
backlight_brightness = 26
backlight_effect = static
backlight_colors = 0 255 255 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1

[IO2308F57800114]
backlight_active = True
backlight_brightness = 26
backlight_effect = static
backlight_colors = 0 255 255 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1

[PM2425H27301923]
dpi_x = 800
dpi_y = 800
poll_rate = 1000
backlight_active = True
backlight_brightness = 25
backlight_effect = static
backlight_colors = 0 255 255 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1
logo_active = True
logo_brightness = 25
logo_effect = static
logo_colors = 0 255 255 0 255 255 0 0 255
logo_speed = 1
logo_wave_dir = 1
scroll_active = True
scroll_brightness = 25
scroll_effect = static
scroll_colors = 0 255 255 0 255 255 0 0 255
scroll_speed = 1
scroll_wave_dir = 1

[UNKNOWN_153200B0_0000]
dpi_x = 2100
dpi_y = 2100
poll_rate = 500
backlight_active = True
backlight_brightness = 25
backlight_effect = static
backlight_colors = 11 254 254 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1
logo_active = True
logo_brightness = 25
logo_effect = static
logo_colors = 11 254 254 0 255 255 0 0 255
logo_speed = 1
logo_wave_dir = 1
scroll_active = True
scroll_brightness = 25
scroll_effect = static
scroll_colors = 11 254 254 0 255 255 0 0 255
scroll_speed = 1
scroll_wave_dir = 1

